[project]
name = "ampav-reallms"
dynamic = ["version"]
description = "REALLMS tooling for the AMPAV environment"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
]
authors = [
    {name = "Ying Feng", email = "yingfeng@iu.edu"},
]

requires-python = ">=3.12"
dependencies = [
    "ampav-core>=0.0.20",
]

[project.scripts]
ampav_reallms_asr = "ampav_reallms_cli.asr:main"

[project.urls]
Homepage = "https://github.com/AMPAV/ampav-reallms"
Repository = "https://github.com/AMPAV/ampav-reallms.git"
Issues = "https://github.com/AMPAV/ampav-reallms/issues"

[tool.setuptools.dynamic]
version = {attr = "ampav.reallms.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["ampav*"]
namespaces = true

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
